name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    env:
      CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), 'skip') }}
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"      
      - name: custom test one
        env:
          CUSTOM_TEST_ONE: ${{ contains(github.event.commits.*.message, 'skip') }}
        run: echo "$CUSTOM_TEST_ONE"      
      - name: custom test two
        env:
          CUSTOM_TEST_TWO: ${{ join(github.event.commits.*.message) }}
        run: echo "$CUSTOM_TEST_TWO"      
      - name: custom test last
        env:
          CUSTOM_TEST_LAST: ${{ contains(join(github.event.commits.*.message), 'skip') }}
        run: echo "$CUSTOM_TEST_LAST"
      - name: custom test four
        if: ${{ env.CONTAINS_SKIP == 'false' }}
        run: echo "it was false!"
      - name: custom test five
        if: ${{ env.CONTAINS_SKIP == 'true' }}
        run: echo "it was true"
      - name: custom test six
        if: |
          ${{ 'false' == 'true' }} &&
          ${{ env.CONTAINS_SKIP == 'true' }} &&          
        run: echo "this should not get printed"





